export type Word={id:string;english:string;turkish:string;emoji:string;example:string;unit:number};
export type Unit={id:number;title:string;turkish:string;emoji:string;words:Word[]};

const raw=[
["Friendship","Arkadaşlık","👥",[["friendly","arkadaş canlısı","👋","She is friendly to everyone."],["reliable","güvenilir","🤝","A reliable friend keeps promises."],["honest","dürüst","💬","An honest person tells the truth."],["supportive","destekleyici","💪","My friends are supportive."],["selfish","bencil","🙅","He is not selfish."],["generous","cömert","🎁","She is generous and helpful."],["trust","güvenmek","🔐","I trust my best friend."],["apologize","özür dilemek","🙏","I apologize for being late."]]],
["Teen Life","Gençlik Hayatı","🎧",[["routine","rutin","🔁","I have a busy routine."],["activity","etkinlik","🏃","I enjoy outdoor activities."],["prefer","tercih etmek","⭐","I prefer reading books."],["relax","rahatlamak","😌","I relax after school."],["concert","konser","🎵","We are going to a concert."],["cultural","kültürel","🎭","I like cultural activities."],["hang out","takılmak","🧑‍🤝‍🧑","We hang out at weekends."],["free time","boş zaman","⏰","I read in my free time."]]],
["In The Kitchen","Mutfakta","🍳",[["ingredient","malzeme","🥕","We need fresh ingredients."],["recipe","tarif","📖","This recipe is easy."],["boil","kaynatmak","♨️","Boil the water first."],["chop","doğramak","🔪","Chop the vegetables."],["slice","dilimlemek","🥒","Slice the bread."],["stir","karıştırmak","🥄","Stir the soup slowly."],["fry","kızartmak","🍳","Fry the onions."],["serve","servis etmek","🍽️","Serve the meal hot."]]],
["On The Phone","Telefonda","📱",[["call","aramak","📞","I will call you later."],["hold on","beklemek","⏳","Please hold on a minute."],["available","müsait","🟢","Is your sister available?"],["message","mesaj","💌","I left a message."],["busy","meşgul","🔴","The line is busy."],["hang up","telefonu kapatmak","📵","Don't hang up."],["connect","bağlamak","🔗","I'll connect you to Mr Smith."],["leave a message","mesaj bırakmak","📝","Can I leave a message?"]]],
["The Internet","İnternet","🌐",[["download","indirmek","⬇️","Download the file."],["upload","yüklemek","⬆️","Upload the photo."],["search","aramak","🔎","I search the Internet."],["website","web sitesi","🖥️","This website is useful."],["account","hesap","👤","Create an account."],["password","şifre","🔑","Keep your password safe."],["online","çevrim içi","🟢","I study online."],["share","paylaşmak","↗️","Don't share your password."]]],
["Adventures","Macera","🧭",[["adventure","macera","🧭","We had an amazing adventure."],["explore","keşfetmek","🗺️","We want to explore the island."],["dangerous","tehlikeli","⚠️","Climbing can be dangerous."],["exciting","heyecan verici","🔥","It was an exciting trip."],["brave","cesur","🦁","She is very brave."],["prefer","tercih etmek","⭐","I prefer adventurous activities."],["experience","deneyim","🎒","It was a great experience."],["travel","seyahat etmek","✈️","I love to travel."]]],
["Tourism","Turizm","✈️",[["tourist","turist","🧳","The city attracts many tourists."],["attraction","turistik yer","📍","The museum is a popular attraction."],["ancient","antik","🏛️","We visited an ancient city."],["historical","tarihi","🏺","Trabzon has historical places."],["souvenir","hediyelik eşya","🎁","I bought a souvenir."],["destination","gidilecek yer","📍","Paris is a popular destination."],["sightseeing","gezi","👀","We went sightseeing."],["brochure","broşür","📄","Read the tourist brochure."]]],
["Chores","Ev İşleri","🧹",[["chore","ev işi","🧹","Doing chores is important."],["vacuum","elektrik süpürgesiyle süpürmek","🧹","I vacuum the carpet."],["laundry","çamaşır","👕","I do the laundry."],["iron","ütülemek","👔","I iron my clothes."],["dust","toz almak","🪶","I dust the furniture."],["mop","paspas yapmak","🧽","We mop the floor."],["take out the garbage","çöpü dışarı çıkarmak","🗑️","Please take out the garbage."],["set the table","sofra kurmak","🍽️","I set the table before dinner."]]],
["Science","Bilim","🔬",[["scientist","bilim insanı","🧑‍🔬","The scientist made a discovery."],["experiment","deney","🧪","We did an experiment."],["discover","keşfetmek","💡","Scientists discover new things."],["invent","icat etmek","⚙️","He invented a useful machine."],["invention","icat","💡","The invention changed our lives."],["research","araştırma","🔬","They conduct scientific research."],["laboratory","laboratuvar","🧪","The students are in the laboratory."],["technology","teknoloji","🤖","Technology develops quickly."]]],
["Natural Forces","Doğal Kuvvetler","🌪️",[["earthquake","deprem","🌍","An earthquake can be dangerous."],["flood","sel","🌊","Heavy rain caused a flood."],["storm","fırtına","⛈️","The storm was very strong."],["tornado","hortum","🌪️","A tornado hit the town."],["drought","kuraklık","🏜️","Drought affects farmers."],["disaster","felaket","🚨","The disaster damaged many buildings."],["destroy","yok etmek","💥","The flood destroyed the bridge."],["damage","zarar vermek","🏚️","The storm damaged houses."]]]
] as const;

export const units:Unit[]=raw.map((u,ui)=>({id:ui+1,title:u[0],turkish:u[1],emoji:u[2],words:u[3].map((w,wi)=>({id:`u${ui+1}-${wi+1}`,english:w[0],turkish:w[1],emoji:w[2],example:w[3],unit:ui+1}))}));
export const allWords=units.flatMap(u=>u.words);
export const getUnit=(id:number)=>units.find(u=>u.id===id);
