import { Word } from "./data";
export const expansion: Word[] = [
{ id:"v-1", english:"buddy", turkish:"kanka", emoji:"🧑‍🤝‍🧑", example:"My buddy lives near me.", unit:1 },
{ id:"v-2", english:"close", turkish:"yakın", emoji:"❤️", example:"We are close friends.", unit:1 },
{ id:"v-3", english:"best friend", turkish:"en iyi arkadaş", emoji:"🏆", example:"She is my best friend.", unit:1 },
{ id:"v-4", english:"respect", turkish:"saygı göstermek", emoji:"🙌", example:"We respect each other.", unit:1 },
{ id:"v-5", english:"teenager", turkish:"ergen", emoji:"🧑", example:"She is a teenager.", unit:2 },
{ id:"v-6", english:"fashion", turkish:"moda", emoji:"👕", example:"She follows fashion.", unit:2 },
{ id:"v-7", english:"hobby", turkish:"hobi", emoji:"🎨", example:"Reading is my hobby.", unit:2 },
{ id:"v-8", english:"join", turkish:"katılmak", emoji:"➕", example:"I want to join the club.", unit:2 },
{ id:"v-9", english:"bake", turkish:"fırında pişirmek", emoji:"🧁", example:"We bake a cake.", unit:3 },
{ id:"v-10", english:"mix", turkish:"karıştırmak", emoji:"🥣", example:"Mix the ingredients.", unit:3 },
{ id:"v-11", english:"pour", turkish:"dökmek", emoji:"🥛", example:"Pour the milk into the bowl.", unit:3 },
{ id:"v-12", english:"add", turkish:"eklemek", emoji:"➕", example:"Add some salt.", unit:3 },
{ id:"v-13", english:"phone call", turkish:"telefon görüşmesi", emoji:"📞", example:"I had a phone call.", unit:4 },
{ id:"v-14", english:"caller", turkish:"arayan kişi", emoji:"📱", example:"The caller left a message.", unit:4 },
{ id:"v-15", english:"wrong number", turkish:"yanlış numara", emoji:"❌", example:"Sorry, wrong number.", unit:4 },
{ id:"v-16", english:"dial", turkish:"numara çevirmek", emoji:"☎️", example:"Dial the number carefully.", unit:4 },
{ id:"v-17", english:"browser", turkish:"tarayıcı", emoji:"🌐", example:"Open your browser.", unit:5 },
{ id:"v-18", english:"click", turkish:"tıklamak", emoji:"🖱️", example:"Click the link.", unit:5 },
{ id:"v-19", english:"link", turkish:"bağlantı", emoji:"🔗", example:"Send me the link.", unit:5 },
{ id:"v-20", english:"email", turkish:"e-posta", emoji:"✉️", example:"I sent an email.", unit:5 },
{ id:"v-21", english:"camp", turkish:"kamp yapmak", emoji:"⛺", example:"We camp in the forest.", unit:6 },
{ id:"v-22", english:"climb", turkish:"tırmanmak", emoji:"🧗", example:"They climb the mountain.", unit:6 },
{ id:"v-23", english:"hike", turkish:"doğa yürüyüşü yapmak", emoji:"🥾", example:"We hike at weekends.", unit:6 },
{ id:"v-24", english:"rafting", turkish:"rafting", emoji:"🛶", example:"Rafting is exciting.", unit:6 },
{ id:"v-25", english:"hotel", turkish:"otel", emoji:"🏨", example:"We stayed at a hotel.", unit:7 },
{ id:"v-26", english:"museum", turkish:"müze", emoji:"🏛️", example:"The museum is famous.", unit:7 },
{ id:"v-27", english:"beach", turkish:"plaj", emoji:"🏖️", example:"The beach is crowded.", unit:7 },
{ id:"v-28", english:"island", turkish:"ada", emoji:"🏝️", example:"They visited a beautiful island.", unit:7 },
{ id:"v-29", english:"clean", turkish:"temizlemek", emoji:"🧼", example:"I clean my room.", unit:8 },
{ id:"v-30", english:"wash the dishes", turkish:"bulaşıkları yıkamak", emoji:"🍽️", example:"I wash the dishes.", unit:8 },
{ id:"v-31", english:"make the bed", turkish:"yatağı yapmak", emoji:"🛏️", example:"I make the bed.", unit:8 },
{ id:"v-32", english:"water the plants", turkish:"bitkileri sulamak", emoji:"🌱", example:"I water the plants.", unit:8 },
{ id:"v-33", english:"energy", turkish:"enerji", emoji:"⚡", example:"Solar energy is useful.", unit:9 },
{ id:"v-34", english:"electricity", turkish:"elektrik", emoji:"💡", example:"We need electricity.", unit:9 },
{ id:"v-35", english:"space", turkish:"uzay", emoji:"🚀", example:"Humans explore space.", unit:9 },
{ id:"v-36", english:"planet", turkish:"gezegen", emoji:"🪐", example:"Earth is our planet.", unit:9 },
{ id:"v-37", english:"tsunami", turkish:"tsunami", emoji:"🌊", example:"The tsunami reached the coast.", unit:10 },
{ id:"v-38", english:"avalanche", turkish:"çığ", emoji:"🏔️", example:"The avalanche blocked the road.", unit:10 },
{ id:"v-39", english:"lightning", turkish:"şimşek", emoji:"⚡", example:"Lightning lit up the sky.", unit:10 },
{ id:"v-40", english:"thunder", turkish:"gök gürültüsü", emoji:"🌩️", example:"I heard loud thunder.", unit:10 }
];
